[package]
name = "llvm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rasendubi/alpha"
publish = false

[dependencies]
llvm-sys = "130"

[build-dependencies]
cc = "1.0"
