[package]
name = "alpha"
version = "0.1.0"
edition = "2018"

[dependencies]
rustyline = "8.0.0"
rustyline-derive = "0.5.0"
logos = "0.12.0"
simple-error = "0.2.3"
llvm = { path = "./llvm" }
llvm-sys = "130"
log = "0.4"
pretty_env_logger = "0.4"
ctor = "0.1.21"
paste = "1.0.6"
lazy_static = "1.4.0"

[workspace]
members = [
  "llvm",
]
