[package]
name = "alpha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
rustyline-derive = "0.5.0"
logos = "0.12.0"
string-interner = "0.14.0"
simple-error = "0.2.3"
llvm = { path = "./llvm" }
llvm-sys = "130"
log = "0.4"
pretty_env_logger = "0.4"

[workspace]
members = [
  "llvm",
]
