name: main
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          directory: "./llvm-build"

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
